export interface PublicHealthFacilitySeed {
  id: string;
  name: string;
  type: string;
  tier: 'Sub-Centre / AAM' | 'Primary Health Centre (PHC)' | 'Rural Hospital (RH)' | 'Sub-District Hospital (SDH)' | 'District Hospital (DH)';
  address: string;
  city: string;
  state: string;
  pincode: string;
  latitude: number;
  longitude: number;
  phone: string;
  emergencyPhone: string;
  email: string;
  totalBeds: number;
  availableBeds: number;
  emergency24x7: boolean;
  teleconsultAvailable: boolean;
  specialistAvailable: boolean;
  diagnosticFacilities: string[];
  languagesSupported: string[];
  averageWaitTimeMinutes: number;
  nqasScore: number; // National Quality Assurance Standards (out of 100)
  departments: {
    name: string;
    department: string;
    totalTokens: number;
    availableTokens: number;
    fee: number;
  }[];
}

export const MAHARASHTRA_PUBLIC_HEALTH_FACILITIES: PublicHealthFacilitySeed[] = [
  {
    id: 'hosp-mh-sc-01',
    name: 'Arogya Vardhini Kendra (Sub-Centre) Medha',
    type: 'Government',
    tier: 'Sub-Centre / AAM',
    address: 'Near Gram Panchayat Bhavan, Medha Valley Road',
    city: 'Medha, Satara',
    state: 'Maharashtra',
    pincode: '415012',
    latitude: 17.7285,
    longitude: 73.8377,
    phone: '02162-245100',
    emergencyPhone: '108',
    email: 'aam.medha@arogya.maharashtra.gov.in',
    totalBeds: 2,
    availableBeds: 2,
    emergency24x7: false,
    teleconsultAvailable: true,
    specialistAvailable: false,
    diagnosticFacilities: ['Rapid Blood Glucose', 'Urine Albumin Test Strip', 'Rapid Hemoglobinometer', 'Blood Pressure Check'],
    languagesSupported: ['Marathi', 'Hindi', 'English'],
    averageWaitTimeMinutes: 10,
    nqasScore: 84,
    departments: [
      { name: 'Primary Wellness & Triage', department: 'General OPD', totalTokens: 40, availableTokens: 25, fee: 0 },
      { name: 'Tele-eSanjeevani Assisted Desk', department: 'Telemedicine', totalTokens: 20, availableTokens: 14, fee: 0 },
      { name: 'Maternal & Child Health Care', department: 'MCH', totalTokens: 30, availableTokens: 18, fee: 0 },
    ],
  },
  {
    id: 'hosp-mh-phc-02',
    name: 'Primary Health Centre (PHC) Mahabaleshwar',
    tier: 'Primary Health Centre (PHC)',
    type: 'Government',
    address: 'Old Tapola Road, Near Rural Bus Depot',
    city: 'Mahabaleshwar, Satara',
    state: 'Maharashtra',
    pincode: '412806',
    latitude: 17.9237,
    longitude: 73.6586,
    phone: '02168-260240',
    emergencyPhone: '108 / 02168-260108',
    email: 'phc.mahabaleshwar@arogya.maharashtra.gov.in',
    totalBeds: 12,
    availableBeds: 5,
    emergency24x7: true,
    teleconsultAvailable: true,
    specialistAvailable: false,
    diagnosticFacilities: ['Routine Blood CBC', 'Rapid Malaria & Dengue Kit', 'Sputum Microscopic Smear (TB)', 'Urine Routine', 'ECG 12-Lead'],
    languagesSupported: ['Marathi', 'Hindi', 'English'],
    averageWaitTimeMinutes: 18,
    nqasScore: 89,
    departments: [
      { name: 'General Medical OPD', department: 'Medicine', totalTokens: 75, availableTokens: 32, fee: 5 },
      { name: '24/7 Normal Labor & Delivery Room', department: 'Obstetrics', totalTokens: 25, availableTokens: 12, fee: 0 },
      { name: 'National Immunization & Child Health', department: 'Pediatrics', totalTokens: 50, availableTokens: 28, fee: 0 },
      { name: 'NCD Clinic (Hypertension & Diabetes)', department: 'Chronic Care', totalTokens: 40, availableTokens: 22, fee: 0 },
    ],
  },
  {
    id: 'hosp-mh-rh-03',
    name: 'Rural Hospital Wai (30-Bedded Community Health Centre)',
    tier: 'Rural Hospital (RH)',
    type: 'Government',
    address: 'Dhamner Road, Opp. Taluka Administrative Complex',
    city: 'Wai, Satara',
    state: 'Maharashtra',
    pincode: '412803',
    latitude: 17.9482,
    longitude: 73.8893,
    phone: '02167-222340',
    emergencyPhone: '108 / 02167-222108',
    email: 'rh.wai@arogya.maharashtra.gov.in',
    totalBeds: 30,
    availableBeds: 8,
    emergency24x7: true,
    teleconsultAvailable: true,
    specialistAvailable: true,
    diagnosticFacilities: ['Digital 300mA X-Ray', 'Obstetric Ultrasound (USG)', 'Automated Hematology Analyzer', 'Blood Storage Unit', 'ECG & Defibrillator', 'CBNAAT TB Lab'],
    languagesSupported: ['Marathi', 'Hindi', 'English'],
    averageWaitTimeMinutes: 25,
    nqasScore: 91,
    departments: [
      { name: 'Emergency Casualty & Trauma Care', department: 'Emergency', totalTokens: 60, availableTokens: 24, fee: 0 },
      { name: 'General Medicine & Specialist OPD', department: 'Medicine', totalTokens: 90, availableTokens: 35, fee: 10 },
      { name: 'Obstetrics & High-Risk Pregnancy Clinic', department: 'Gynecology', totalTokens: 50, availableTokens: 18, fee: 10 },
      { name: 'Pediatrics & Sick Newborn Care Unit (NBSU)', department: 'Pediatrics', totalTokens: 40, availableTokens: 15, fee: 0 },
      { name: 'Minor Operation Theatre & Orthopedics', department: 'Surgery', totalTokens: 30, availableTokens: 12, fee: 15 },
    ],
  },
  {
    id: 'hosp-mh-sdh-04',
    name: 'Sub-District Hospital Karad (100-Bedded First Referral Unit)',
    tier: 'Sub-District Hospital (SDH)',
    type: 'Government',
    address: 'Near Old Bus Stand, Somwar Peth',
    city: 'Karad, Satara',
    state: 'Maharashtra',
    pincode: '415110',
    latitude: 17.2885,
    longitude: 74.1844,
    phone: '02164-222510',
    emergencyPhone: '108 / 02164-222108',
    email: 'sdh.karad@arogya.maharashtra.gov.in',
    totalBeds: 100,
    availableBeds: 26,
    emergency24x7: true,
    teleconsultAvailable: true,
    specialistAvailable: true,
    diagnosticFacilities: ['Color Doppler 4D USG', '500mA Digital X-Ray', 'Fully Automated Biochemistry Analyzer', 'Licensed Blood Bank', 'Special Newborn Care Unit (SNCU)', '10-Bed HDU/ICU'],
    languagesSupported: ['Marathi', 'Hindi', 'English'],
    averageWaitTimeMinutes: 22,
    nqasScore: 93,
    departments: [
      { name: 'Emergency Trauma & Resuscitation Center', department: 'Emergency', totalTokens: 100, availableTokens: 45, fee: 0 },
      { name: 'Internal Medicine & Cardiology Consult', department: 'Medicine', totalTokens: 120, availableTokens: 42, fee: 10 },
      { name: 'General Surgery & Laparoscopy', department: 'Surgery', totalTokens: 80, availableTokens: 30, fee: 15 },
      { name: 'Maternity Ward & Caesarean Section Unit', department: 'Gynecology', totalTokens: 90, availableTokens: 34, fee: 0 },
      { name: 'Ophthalmology & Cataract Screening', department: 'Eye Care', totalTokens: 60, availableTokens: 25, fee: 10 },
    ],
  },
  {
    id: 'hosp-mh-dh-05',
    name: 'Chhatrapati Shivaji Maharaj District Civil Hospital Satara',
    tier: 'District Hospital (DH)',
    type: 'Government',
    address: 'Sadar Bazar, Near Collector Office',
    city: 'Satara',
    state: 'Maharashtra',
    pincode: '415001',
    latitude: 17.6805,
    longitude: 73.9934,
    phone: '02162-234500',
    emergencyPhone: '108 / 02162-234108',
    email: 'civilhospital.satara@arogya.maharashtra.gov.in',
    totalBeds: 450,
    availableBeds: 82,
    emergency24x7: true,
    teleconsultAvailable: true,
    specialistAvailable: true,
    diagnosticFacilities: ['128-Slice CT Scan', '1.5T MRI', 'Digital Cath Lab', 'Hemodialysis Unit (12 Machines)', 'Component Blood Bank', 'Level-3 Trauma ICU', 'Tele-ICU Hub'],
    languagesSupported: ['Marathi', 'Hindi', 'English'],
    averageWaitTimeMinutes: 30,
    nqasScore: 96,
    departments: [
      { name: 'Casualty & Critical Care Trauma Complex', department: 'Emergency', totalTokens: 200, availableTokens: 85, fee: 0 },
      { name: 'Cardiology & Tele-ECG Expert Desk', department: 'Cardiology', totalTokens: 100, availableTokens: 38, fee: 20 },
      { name: 'Neurology & Stroke Intervention Unit', department: 'Neurology', totalTokens: 80, availableTokens: 26, fee: 20 },
      { name: 'Orthopedic & Joint Trauma Unit', department: 'Orthopedics', totalTokens: 120, availableTokens: 48, fee: 15 },
      { name: 'Super-Speciality Teleconsultation Hub', department: 'Telemedicine', totalTokens: 150, availableTokens: 72, fee: 0 },
      { name: 'Dialysis & Nephrology Care', department: 'Nephrology', totalTokens: 50, availableTokens: 16, fee: 0 },
    ],
  },
];

export const SEED_ESSENTIAL_MEDICINES = [
  {
    medicine_name: 'Paracetamol 500mg Tablets',
    generic_name: 'Paracetamol IP',
    category: 'Analgesic',
    dosage_form: 'Tablet',
    facility_tier: 'Sub-Centre / AAM',
    stock_count: 850,
    min_threshold: 150,
    status: 'In Stock' as const,
    batch_number: 'PCM-2026-08',
    expiry_date: '2027-11-30',
  },
  {
    medicine_name: 'Amoxicillin 500mg Capsules',
    generic_name: 'Amoxicillin Trihydrate IP',
    category: 'Antibiotic',
    dosage_form: 'Capsule',
    facility_tier: 'Primary Health Centre (PHC)',
    stock_count: 420,
    min_threshold: 100,
    status: 'In Stock' as const,
    batch_number: 'AMX-2026-04',
    expiry_date: '2027-08-15',
  },
  {
    medicine_name: 'Metformin 500mg Extended Release',
    generic_name: 'Metformin Hydrochloride IP',
    category: 'Anti-Diabetic',
    dosage_form: 'Tablet',
    facility_tier: 'Primary Health Centre (PHC)',
    stock_count: 38,
    min_threshold: 80,
    status: 'Low Stock' as const,
    batch_number: 'MET-2026-11',
    expiry_date: '2027-09-30',
  },
  {
    medicine_name: 'Amlodipine 5mg Tablets',
    generic_name: 'Amlodipine Besylate IP',
    category: 'Anti-Hypertensive',
    dosage_form: 'Tablet',
    facility_tier: 'Rural Hospital (RH)',
    stock_count: 650,
    min_threshold: 120,
    status: 'In Stock' as const,
    batch_number: 'AML-2026-09',
    expiry_date: '2028-01-20',
  },
  {
    medicine_name: 'Iron and Folic Acid (IFA) Red Tablets',
    generic_name: 'Ferrous Sulphate 100mg + Folic Acid 0.5mg',
    category: 'Maternal Health',
    dosage_form: 'Tablet',
    facility_tier: 'Sub-Centre / AAM',
    stock_count: 1400,
    min_threshold: 200,
    status: 'In Stock' as const,
    batch_number: 'IFA-2026-12',
    expiry_date: '2027-12-31',
  },
  {
    medicine_name: 'Oral Rehydration Salts (ORS) WHO Formula',
    generic_name: 'Sodium Chloride, Potassium Chloride, Sodium Citrate',
    category: 'Emergency / Antidote',
    dosage_form: 'Sachet',
    facility_tier: 'Sub-Centre / AAM',
    stock_count: 600,
    min_threshold: 100,
    status: 'In Stock' as const,
    batch_number: 'ORS-2026-03',
    expiry_date: '2028-05-15',
  },
  {
    medicine_name: 'Polyvalent Anti-Snake Venom (ASV) Lyophilized',
    generic_name: 'Equine Polyvalent Snake Antivenom IP',
    category: 'Emergency / Antidote',
    dosage_form: 'Injection',
    facility_tier: 'Rural Hospital (RH)',
    stock_count: 35,
    min_threshold: 15,
    status: 'In Stock' as const,
    batch_number: 'ASV-2026-01',
    expiry_date: '2027-10-31',
  },
  {
    medicine_name: 'Anti-Rabies Vaccine (ARV) Cell Culture',
    generic_name: 'Purified Chick Embryo Cell Rabies Vaccine IP',
    category: 'Vaccine',
    dosage_form: 'Injection',
    facility_tier: 'Rural Hospital (RH)',
    stock_count: 18,
    min_threshold: 20,
    status: 'Low Stock' as const,
    batch_number: 'ARV-2026-07',
    expiry_date: '2027-06-30',
  },
  {
    medicine_name: 'Insulin Human Regular 40 IU/ml',
    generic_name: 'Human Recombinant Soluble Insulin IP',
    category: 'Anti-Diabetic',
    dosage_form: 'Injection',
    facility_tier: 'District Hospital (DH)',
    stock_count: 120,
    min_threshold: 30,
    status: 'In Stock' as const,
    batch_number: 'INS-2026-05',
    expiry_date: '2027-04-15',
  },
  {
    medicine_name: 'Albendazole 400mg Chewable',
    generic_name: 'Albendazole IP',
    category: 'Maternal Health',
    dosage_form: 'Tablet',
    facility_tier: 'Sub-Centre / AAM',
    stock_count: 480,
    min_threshold: 100,
    status: 'In Stock' as const,
    batch_number: 'ALB-2026-02',
    expiry_date: '2028-02-28',
  },
];

export const SEED_DIAGNOSTICS = [
  {
    service_name: 'Complete Blood Count (CBC) with Platelets',
    category: 'Pathology',
    facility_tier: 'Primary Health Centre (PHC)',
    description: 'Automated 5-part differential CBC using hematology analyzer.',
    equipment_status: 'FUNCTIONAL' as const,
    availability_status: 'AVAILABLE' as const,
    booking_status: 'AVAILABLE' as const,
    technician_available: true,
    fee: 0,
    fee_verified: true,
    opening_time: '08:00',
    closing_time: '14:00',
    tat_hours: 2,
    verification_status: 'VERIFIED' as const,
    source: 'facility_reported',
  },
  {
    service_name: 'Sputum Smear & CBNAAT for Tuberculosis (GeneXpert)',
    category: 'Microbiology',
    facility_tier: 'Rural Hospital (RH)',
    description: 'Cartridge Based Nucleic Acid Amplification Test for M. tuberculosis and Rifampicin resistance.',
    equipment_status: 'FUNCTIONAL' as const,
    availability_status: 'AVAILABLE' as const,
    booking_status: 'AVAILABLE' as const,
    technician_available: true,
    fee: 0,
    fee_verified: true,
    opening_time: '08:00',
    closing_time: '16:00',
    tat_hours: 4,
    verification_status: 'VERIFIED' as const,
    source: 'nikshay_portal',
  },
  {
    service_name: 'Digital Chest X-Ray (PA View)',
    category: 'Radiology',
    facility_tier: 'Rural Hospital (RH)',
    description: 'Computed Radiography (CR) system for posteroanterior chest imaging.',
    equipment_status: 'UNDER_MAINTENANCE' as const,
    availability_status: 'UNAVAILABLE' as const,
    booking_status: 'UNAVAILABLE' as const,
    technician_available: true,
    fee: 0,
    fee_verified: false,
    opening_time: '08:30',
    closing_time: '13:30',
    tat_hours: 1,
    verification_status: 'PENDING_VERIFICATION' as const,
    source: 'facility_reported',
  },
  {
    service_name: 'Obstetric 2D Ultrasound & Anomaly Scan',
    category: 'Radiology',
    facility_tier: 'Sub-District Hospital (SDH)',
    description: '2D transabdominal obstetric ultrasonography including anomaly screening.',
    equipment_status: 'FUNCTIONAL' as const,
    availability_status: 'AVAILABLE' as const,
    booking_status: 'AVAILABLE' as const,
    technician_available: null,
    fee: null,
    fee_verified: false,
    opening_time: '09:00',
    closing_time: '15:00',
    tat_hours: 1,
    verification_status: 'UNVERIFIED' as const,
    source: 'facility_reported',
  },
  {
    service_name: '12-Lead Electrocardiogram (ECG) with Tele-Cardiology Report',
    category: 'Cardiology',
    facility_tier: 'Primary Health Centre (PHC)',
    description: 'Standard 12-lead resting ECG with tele-interpretation via NCD App.',
    equipment_status: 'FUNCTIONAL' as const,
    availability_status: 'AVAILABLE' as const,
    booking_status: 'AVAILABLE' as const,
    technician_available: true,
    fee: 0,
    fee_verified: true,
    opening_time: null,
    closing_time: null,
    tat_hours: 1,
    verification_status: 'VERIFIED' as const,
    source: 'ncd_portal',
  },
  {
    service_name: 'Non-Contrast Computed Tomography (NCCT Brain 128-Slice)',
    category: 'Radiology',
    facility_tier: 'District Hospital (DH)',
    description: '128-slice CT scanner for non-contrast head imaging.',
    equipment_status: 'UNKNOWN' as const,
    availability_status: 'UNKNOWN' as const,
    booking_status: 'UNKNOWN' as const,
    technician_available: null,
    fee: 300,
    fee_verified: false,
    opening_time: null,
    closing_time: null,
    tat_hours: null,
    verification_status: 'UNVERIFIED' as const,
    source: 'directory_listing',
  },
  {
    service_name: 'Glycated Hemoglobin (HbA1c Analyzer)',
    category: 'Pathology',
    facility_tier: 'Rural Hospital (RH)',
    description: 'Point-of-care HbA1c testing for diabetes monitoring.',
    equipment_status: 'OUT_OF_SERVICE' as const,
    availability_status: 'UNAVAILABLE' as const,
    booking_status: 'UNAVAILABLE' as const,
    technician_available: false,
    fee: 0,
    fee_verified: true,
    opening_time: '08:00',
    closing_time: '14:00',
    tat_hours: 3,
    verification_status: 'VERIFIED' as const,
    source: 'facility_reported',
  },
];

export const SEED_HIGH_RISK_PATIENTS = [
  {
    patient_name: 'Sunita Devi (Age 60, Mahabaleshwar Rural)',
    cohort_type: 'Chronic NCD (Hypertension & Type 2 Diabetes)',
    risk_level: 'High Risk',
    primary_condition: 'Uncontrolled Essential Hypertension (BP 168/102) with diabetic peripheral neuropathy',
    current_milestone: 'Quarterly Serum Creatinine, HbA1c & Fundus Examination Due',
    next_due_date: 'Tomorrow, 09:30 AM',
    status: 'Overdue',
    assigned_asha_name: 'ASHA Tai Sunanda Kadam',
    follow_up_notes: 'Patient faces 32km travel friction to Rural Hospital. ASHA advised doorstep BP monitoring and assisted teleconsultation scheduled.',
  },
  {
    patient_name: 'Anandi Deepak Shinde (Age 24, Medha Village)',
    cohort_type: 'Maternal (HRP)',
    risk_level: 'Critical',
    primary_condition: '3rd Trimester High-Risk Pregnancy (34 Weeks) with Severe Anemia (Hb 7.2 g/dL)',
    current_milestone: '4th ANC Visit + Intravenous Iron Sucrose Infusion + Ultrasound Doppler',
    next_due_date: 'Within 3 Days',
    status: 'Active',
    assigned_asha_name: 'ASHA Tai Vaishali Bhosale',
    follow_up_notes: 'Referred from Sub-Centre Medha to Rural Hospital Wai. Free 102 Janani Shishu transit arranged for delivery preparedness.',
  },
  {
    patient_name: 'Master Aarav Sachin Jadhav (Age 14 Weeks, Wai Rural)',
    cohort_type: 'Child (Immunization)',
    risk_level: 'Moderate Risk',
    primary_condition: 'National Immunization Schedule Adherence',
    current_milestone: 'Pentavalent-3, OPV-3, Rotavirus-3 & Fractional IPV-2 Due',
    next_due_date: 'This Thursday (Mamata Diwas / Village Health Sanitation Nutrition Day)',
    status: 'Active',
    assigned_asha_name: 'ASHA Tai Sunanda Kadam',
    follow_up_notes: 'ASHA verified cold chain vaccine availability at PHC sub-depot. Mother reminded via vernacular SMS alert.',
  },
  {
    patient_name: 'Rameshwar Tukaram More (Age 52, Koregaon Village)',
    cohort_type: 'Tuberculosis (DOTS)',
    risk_level: 'High Risk',
    primary_condition: 'Microbiologically Confirmed Pulmonary Tuberculosis (Category-1 Intensive Phase)',
    current_milestone: 'Month 2 Sputum Conversion Smear + Daily Fixed Dose Combination (FDC) Adherence',
    next_due_date: 'In 5 Days',
    status: 'Active',
    assigned_asha_name: 'CHO Dr. Nilesh Patil',
    follow_up_notes: '100% blister pack adherence logged via Nikshay direct-benefit transfer dashboard.',
  },
];

export const SEED_FRONTLINE_TASKS = [
  {
    worker_id: 'asha-worker-01',
    worker_name: 'Sunanda Kadam (ASHA Worker)',
    worker_role: 'ASHA',
    village_name: 'Medha Valley, Satara',
    beneficiary_name: 'Sunita Devi',
    beneficiary_phone: '98223-11045',
    task_type: 'Doorstep Triage & BP Check',
    due_date: 'Today, 11:00 AM',
    status: 'Pending',
    notes: 'Record digital BP, check medicine stock for Amlodipine 5mg, sync vitals to PHIS portal.',
  },
  {
    worker_id: 'asha-worker-01',
    worker_name: 'Sunanda Kadam (ASHA Worker)',
    worker_role: 'ASHA',
    village_name: 'Medha Valley, Satara',
    beneficiary_name: 'Anandi Shinde',
    beneficiary_phone: '97654-22190',
    task_type: 'ANC Home Visit (High-Risk Anemia)',
    due_date: 'Tomorrow, 09:00 AM',
    status: 'Pending',
    notes: 'Verify IFA tablet consumption, check pedal edema, confirm 102 ambulance route for Wai delivery.',
  },
  {
    worker_id: 'asha-worker-01',
    worker_name: 'Sunanda Kadam (ASHA Worker)',
    worker_role: 'ASHA',
    village_name: 'Medha Valley, Satara',
    beneficiary_name: 'Master Aarav Jadhav',
    beneficiary_phone: '94210-99881',
    task_type: 'Child Immunization Due Reminder',
    due_date: 'Thursday, 10:00 AM',
    status: 'Pending',
    notes: 'Mamata Diwas session at Anganwadi-2. Verify MCP card entry for Pentavalent-3.',
  },
  {
    worker_id: 'cho-worker-02',
    worker_name: 'Dr. Nilesh Patil (Community Health Officer)',
    worker_role: 'CHO',
    village_name: 'Arogya Vardhini Kendra Medha',
    beneficiary_name: 'Tukaram Jagtap (Age 68)',
    beneficiary_phone: '98901-45672',
    task_type: 'Assisted Teleconsultation with Civil Hospital Satara',
    due_date: 'Today, 02:30 PM',
    status: 'Pending',
    notes: 'Connect with Dr. Rajesh Deshmukh (MD Medicine) via eSanjeevani portal for diabetic foot assessment.',
  },
];
