import { Router } from 'express';
import authRoutes from './authRoutes.js';
import patientRoutes from './patientRoutes.js';
import hospitalRoutes from './hospitalRoutes.js';
import requestRoutes from './requestRoutes.js';
import consentRoutes from './consentRoutes.js';
import documentRoutes from './documentRoutes.js';
import simulationRoutes from './simulationRoutes.js';
import interventionRoutes from './interventionRoutes.js';
import adminRoutes from './adminRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import languageRoutes from './languageRoutes.js';
import publicHealthRoutes from './publicHealthRoutes.js';
import doctorRoutes from './doctorRoutes.js';
import ashaRoutes from './ashaRoutes.js';
import governmentRoutes from './governmentRoutes.js';
import queueRoutes from './queueRoutes.js';
import frictionReportRoutes from './frictionReportRoutes.js';
import digitalTwinRoutes from './digitalTwinRoutes.js';
import aiRoutes from './aiRoutes.js';
import appointmentVoiceRoutes from './appointmentVoiceRoutes.js';
import webhookRoutes from './webhookRoutes.js';
import officerWorkflowRoutes from './officerWorkflowRoutes.js';
import multiLevelFrictionRoutes from './multiLevelFrictionRoutes.js';

const router = Router();

router.use('/appointments', appointmentVoiceRoutes);
router.use('/webhooks', webhookRoutes);

router.use('/auth', authRoutes);
router.use('/patients', patientRoutes);
router.use('/hospitals', hospitalRoutes);
router.use('/requests', requestRoutes);
router.use('/consents', consentRoutes);
router.use('/documents', documentRoutes);
router.use('/simulation', simulationRoutes);
router.use('/simulations', simulationRoutes);
router.use('/interventions', interventionRoutes);
router.use('/admin', adminRoutes);
router.use('/notifications', notificationRoutes);
router.use('/languages', languageRoutes);
router.use('/public-health', publicHealthRoutes);
router.use('/doctors', doctorRoutes);
router.use('/asha', ashaRoutes);
router.use('/government/workflow', officerWorkflowRoutes);
router.use('/admin/workflow', officerWorkflowRoutes);
router.use('/friction', multiLevelFrictionRoutes);
router.use('/government/friction', multiLevelFrictionRoutes);
router.use('/government', governmentRoutes);
router.use('/queue', queueRoutes);
router.use('/friction-reports', frictionReportRoutes);
router.use('/digital-twin', digitalTwinRoutes);
router.use('/ai', aiRoutes);

export default router;
